### ISSUE TITLE
Consumer not being instrumented for dynatrace

### ISSUE THREAD

**Issue by dlopes7** [MatheusGeiger/django-with-instrumentation#1]
When the consumer starts with `AUTODYNATRACE_FORKABLE` set to `true`, what is happening is that we are telling the OneAgent SDK that we want to instrument child processes ONLY.

There are no child processes, the python process running `manage.py` is the only process, so the SDK becomes unusable in this process (the parent)

This is documented here: https://github.com/Dynatrace/OneAgent-SDK-for-C#using-the-dynatrace-oneagent-sdk-with-forked-child-processes-only-available-on-linux 

I understand that this can be frustrating, but it is a limitation of the OneAgent SDK for python being a wrapper around the OneAgent SDK for C/C++ and the nature of the injection happening on that module.

To fix this, set `AUTODYNATRACE_FORKABLE=false` for the consumer container, maybe overriding the environment variable [here ](https://github.com/MatheusGeiger/django-with-instrumentation/blob/master/dynatrace-instrumentation/cluster-and-oneagent-installation/k8s-manifests/2-service-and-deployment.yaml#L75) 

With:

```yaml
env:
   - name: AUTODYNATRACE_FORKABLE  
     value: "false"
```

With this you get logs:

```
2023-07-10 16:37:15.562 UTC [69b65d79] info    [onesdk] Loaded extension API techtype.
2023-07-10 16:37:15,562: 11 DEBUG autodynatrace - init: Initialized autodynatrace with AgentState: 0
2023-07-10 16:37:15,564: 11 DEBUG autodynatrace - instrument_lib: Attempting to instrument urllib
2023-07-10 16:37:15,575: 11 DEBUG autodynatrace - instrument_lib: Attempting to instrument subprocess
```

And can see end to end tracing:

![image](https://github.com/MatheusGeiger/django-with-instrumentation/assets/10208081/2dde6332-32e8-4465-90c8-342d579b6422)

![image](https://github.com/MatheusGeiger/django-with-instrumentation/assets/10208081/19377c9f-316c-408b-adc8-639eccffcf74)

**Comment by MatheusGeiger** [comment]
@dlopes7 Many thanks for help us to understand this case. With the  `AUTODYNATRACE_FORKABLE` with the false value we can see the communication from publisher and consumer. 

Now we are trying to discover the motivation for not showing the consumer actions(database hit, other publishers, etc..)
<img width="1233" alt="Screenshot 2023-07-11 at 16 28 01" src="https://github.com/MatheusGeiger/django-with-instrumentation/assets/22987079/40077679-64b7-4073-bae7-6a3b01b471c2">


We have a database's actions inside the consumer code, but it is not shown in dynatrace.

for one test we include the `@autodynatrace.trace` decorator below the consumer method
```python
@autodynatrace.trace
def consumer(payload: Payload) -> None:
```
and this action creates a new "service" and we have the traces inside the consumer but with other trace_id.
<img width="1176" alt="Screenshot 2023-07-11 at 16 27 08" src="https://github.com/MatheusGeiger/django-with-instrumentation/assets/22987079/cd4ee2fe-5947-4da7-a9da-42a4b2ab06f2">


For this scenario, I'm trying to correlate the process. Did you know how to set the sdk context to continue from the existent `trace_id`?

Using opentelemetry we resolve this problem using [this](https://github.com/juntossomosmais/opentelemetry-instrumentation-django-stomp/blob/main/opentelemetry_instrumentation_django_stomp/instrumentors/consumer_instrument.py#L63) approach. I'm attach the context using [attach context. ](https://github.com/juntossomosmais/opentelemetry-instrumentation-django-stomp/blob/3239f964e85ed31a1f042e66e834c5c20998aa70/opentelemetry_instrumentation_django_stomp/utils/traced_thread_pool_executor.py#L23)

**Comment by dlopes7** [comment]
That is strange that these calls are not being picket OOTB, I will take a look.

Adding `@autodynatrace.trace` would force a broken correlation, because it adds a `Custom Service`, a type of trace that does not correlate purepaths, losing the information about upstream

**Comment by dlopes7** [comment]
Disconnection seems to be because of 

```
{"levelname": "DEBUG", "asctime": "2023-07-12 16:51:59,362", "request_id": "none", "name": "autodynatrace", "message": "Tracing downstream thread execution", "span_id": "be02c2d21d78587f", "trace_id": "5fb24d3f61b711d63e7a3a6fafcc7d54"}
2023-07-12 16:51:59.357 UTC [00000021] info    [native] NOTE: Ignoring in-process link: already tracing another operation.
CALLBACK DIAG NOTE: Ignoring in-process link: already tracing another operation.
```

**Comment by MatheusGeiger** [comment]
@dlopes7 I [removed](https://github.com/MatheusGeiger/django-with-instrumentation/commit/75d8197f7cd9b845cfca8fc456a20e8e59f592d9) the force instrumentation for Threads (used in consumer processing). The behavior continues the same. 
The trace from the consumer doesn't appear on the "main" tracer.

**Comment by MatheusGeiger** [comment]
@dlopes7 Many thanks for all your help in this case. 

We fix the consumer instrumentation in this [commit](https://github.com/MatheusGeiger/django-with-instrumentation/commit/a6322c2e8c666eb8ebbacbdca43b9e74f87f2fe9).

<img width="1261" alt="Screenshot 2023-07-14 at 09 29 36" src="https://github.com/MatheusGeiger/django-with-instrumentation/assets/22987079/3ae17901-7c3e-46cb-ad18-906c953146a4">

Explaining the problem:

The consumer code with [django-stomp](https://github.com/juntossomosmais/django-stomp) has a particular functionality, the message process use [thread_pool_executor](https://github.com/juntossomosmais/django-stomp/blob/master/django_stomp/services/consumer.py#L101) to call the business rule callback function, the callback function is responsible to interact with others services like database, another queue, requests, and others.

With this flow, the linking from the incoming message and the callback function is not made because the callback execution occurs inside one thread_pool.

We change the instrumentation code to include a wrapper into the `callback function` for consumers and `send` from the publisher.

With these changes the instrumentation works as expected.

The code structure is similar to this draw below:
<img width="2275" alt="dynatrace" src="https://github.com/MatheusGeiger/django-with-instrumentation/assets/22987079/37a09f89-0752-4b02-99b5-20c66c0e0cac">
